package Java;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import java.util.function.Function;
import java.util.function.Supplier;

public class UserService {
    private static final String CHARACTERS = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";

    public static void main(String[] args) {

     //Question 2:Create List of Users from List of Employees.


        Employee employee = new Employee("John", "Doe", 1, "23/10/1998", new BigDecimal(2000), "HR");
        // Use the Function to convert Employee to User
     // Write java 8 function which will take Employee input and will return object of class User.
        Function<Employee,User> userConverter = UserService :: convertToUser;
        User user = userConverter.apply(employee);
        System.out.println(user);

        List<Employee> employeeList = createEmployeeList();

                // Convert the List<Employee> to List<User> using the function
                List<User> userList = employeeList.stream()
                        .map(employeeToUserConverter)
                        .toList();

        // Print the userList or perform any other operations
        userList.forEach(System.out::println);


    }
    private static List<Employee> createEmployeeList() {
        List<Employee> employeeList = new ArrayList<>();
        employeeList.add(new Employee("John", "Doe", 1,"23/10/1998" ,new BigDecimal(2000), "HR"));
        employeeList.add(new Employee("Jane", "Smith", 2, "23/10/1998",new BigDecimal(2500), "IT"));
        employeeList.add(new Employee("Bob", "Johnson", 3, "23/10/1998",new BigDecimal(3000), "Finance"));
        return employeeList;
    }

    public static Function<Employee, User> employeeToUserConverter = employee -> {
      //  UserName should be firstName+LastName+YearOfBirth+id and password will be generated by supplier above, use id from Employee class as id.

        User user = new User();
        user.setUsername(employee.getFirstName() + employee.getLastName() +   employee.getDateOfBirth().getYear()  + employee.getId());
        user.setPassword(generateRandomPassword());
        user.setId(employee.getId());
        return user;
    };

    private static User convertToUser(Employee employee) {
    //    Write java 8 Supplier which will generate 16 Character random password as String.
        Supplier<String> passwordSupplier = UserService::generateRandomPassword;

        String username = employee.getFirstName() + employee.getLastName();

        if (employee.getDateOfBirth() != null) {
            username += employee.getDateOfBirth().getYear();
        }

        username += employee.getId();

        String password = passwordSupplier.get();
        return new User(username, employee.getId(), password);
    }



    private static String generateRandomPassword() {
        Random random = new Random();
        StringBuilder password = new StringBuilder();
        for (int i = 0; i < 16; i++) {
            int index = random.nextInt(CHARACTERS.length());
            password.append(CHARACTERS.charAt(index));
        }

        return password.toString();
    }
}
